### ISSUE TITLE
Feature: Trait Values Inline Editor

### ISSUE THREAD

**Issue by kevinfaveri** [theskeletoncrew/treat-toolbox#13]
I think software like this one benefits a ton from having editing of stuff happening inline. Especially on the values of traits page for rarities and stuff.

**Comment by skeletoncrewrip** [comment]
another good suggestion. have a few functional tasks to get through, but then refining workflows for speed is a clear win.

**Comment by KitanGarcia** [comment]
@kevinfaveri @skeletoncrewrip I just got this working and got the PR out. Do let me know your thoughts and if I should change anything. Thanks!
