### ISSUE TITLE
Feature: Allow for Metadata adjustments

### ISSUE THREAD

**Issue by mhvuze** [theskeletoncrew/treat-toolbox#20]
First off: Thanks for the toolkit! It's really nice to work with and there have already been some great suggestions for improvement made by other users that I thought about as well when testing a collection.

Something else I'd like to suggest is adding customisation options for metadata as follows:

- Allow customising the `name` property and do not force the "symbol #N" format here
- Allow customising the `external_url` property: custom url format / default to homepage for all / leave blank
- Allow customising the `family` property and do not force the project name here

**Comment by skeletoncrewrip** [comment]
`Allow customizing the name property and do not force the "symbol #N" format here`

This is now available for name. Should be easy to add it for `external_url` too based on this change.

**Comment by cosimo-rip** [comment]
This is also now implemented for `external_url`.
