### ISSUE TITLE
Composite export stuck on 100%

### ISSUE THREAD

**Issue by musty-xyz** [theskeletoncrew/treat-toolbox#23]
![image](https://user-images.githubusercontent.com/93217594/138932757-d78657ce-80de-49f8-ad0b-f778e910c1a4.png)

Hello, I've had an issue where the past few times I've tried to export a composite, the loading bar slowly rises, but when it reaches 100%, it simply gets stuck and the download modal doesn't appear, even after several hours of leaving the browser running.

I'm running Windows 10, if that influences anything, and am generating a collection of 5555 assets.

**Comment by cosimo-rip** [comment]
Please try the latest PR: https://github.com/theskeletoncrew/treat-toolbox/pull/31
