### ISSUE TITLE
Composite Generation Issue - Input File contains unsupported image format

### ISSUE THREAD

**Issue by Mathieuduverney** [theskeletoncrew/treat-toolbox#28]
Hi all !

First thanks for the tool and the set up guide, very easy to understand and clear.

I had no issue until the last step of composite generations.

Once I click on Generate Composites, my progress bar is stuck to 0%

I checked the logs in my firebase terminal and apparently I have an issue with the image format, which are in png.

Do you guys have encounter this issue?

<img width="1548" alt="Screenshot 2021-10-30 at 6 24 07 PM" src="https://user-images.githubusercontent.com/15248842/139529469-1ad1d6b1-d347-40b7-9f4a-08fdf51e23bd.png">

Thanks!

**Comment by Mathieuduverney** [comment]
Ok I've ran the test-image project, and it's perfectly working ...
So it might be an issue with the images ... Does someone has any ideas??

is there different types of png?
I really dont understand

**Comment by Mathieuduverney** [comment]
For those having this issue

I resized the png to 2100x2100 and it's now working

**Comment by cosimo-rip** [comment]
interesting, thanks! it could have been the size, but more likely just resaving the png resolved the format issue.
