### ISSUE TITLE
Error when trying to create a Drop without a User Group

### ISSUE THREAD

**Issue by walter-grace** [theskeletoncrew/treat-toolbox#3]
FirebaseError: Function addDoc() called with invalid data. Unsupported field value: undefined (found in field userGroupId in document projects/GssXAEKS31qFUcbk0Ocx/collections/KwwgYiwVOBEZxFImOp7f)

Running into this error and also cant input a creator in the dropdown field. Any suggestion?

**Comment by bruhjimbo** [comment]
I am also having the same problem. please let me know if you find a solution!
