### ISSUE TITLE
BUG WITH CREATOR in .JSON

### ISSUE THREAD

**Issue by MOONSKYLER** [theskeletoncrew/treat-toolbox#34]
Hello everyone,

Becarefull with new release there is a small bug in the export .JSON.
The creator properties are not report in .JSON so the fees from royalties missing.

**For the moment the workaround :**
updating candy-machine.js and settle your info in code 

"creators": {
            "address": "XXXXXXXXX",
            "share": 100
        }

**Comment by cosimo-rip** [comment]
Thanks! should now be fixed by this commit: https://github.com/theskeletoncrew/treat-toolbox/commit/fc0c62768e5bf0aa1f33fca33b7268c4026a58ae
