### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by bruhjimbo** [theskeletoncrew/treat-toolbox#4]
Unhandled Runtime Error
FirebaseError: Function addDoc() called with invalid data. Unsupported field value: undefined (found in field userGroupId in document projects/jdnw8ZhXfyvxkin0XSmx/collections/HSEnXCcWQyoV69SJZnGg)

it won't let me select a creator under create drop.

![image](https://user-images.githubusercontent.com/77355504/137620148-017f7d55-db32-418a-b60e-bd2f7193308d.png)

it just shows a black bar

**Comment by skeletoncrewrip** [comment]
hmm did you add a user group?

**Comment by bruhjimbo** [comment]
> hmm did you add a user group?

Ok I see, i didn't make a group. It works now and i uploaded all my images and data but new problem occur when trying to composite. I will open new issue because it is different for it
