### ISSUE TITLE
Allow multiple art configuration

### ISSUE THREAD

**Issue by yoboitel** [theskeletoncrew/treat-toolbox#40]
Hey, 
First of all your product is awesome, and very useful !
I was just wondering if it was possible to add something where we can create multiple configuration of art.
Eg : A woman base body with certain items, And another one with a boy base body and certain items ?

I'm not sure if this was very clear but it would be awesome if it can do this. I saw it was doable in the hashlip generative art.

Best.

**Comment by skeletoncrewrip** [comment]
Indeed! This is the main use case we created Trait Sets for. Essentially - your "woman" traits would belong to one trait set, and your "boy" trait set would be another. You can also have traits that belong to both trait sets. 

Feel free to re-open if that doesnt answer your question
