### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by jonathanort** [theskeletoncrew/treat-toolbox#45]
Hi, we're receiving an error when trying to export a large sum of items. Smaller amounts worked fine.

Any ideas on how to fix it?

constructing item 0
>  constructing item 1
>  events.js:292
>        throw er; // Unhandled 'error' event
>        ^
>
>  GaxiosError: Request failed with status code 400
>      at Gaxios._request (/Users/jonathan/Development/treat-toolbox/functions/node_modules/gaxios/build/src/gaxios.js:129:23)
>      at processTicksAndRejections (internal/process/task_queues.js:97:5)
>      at async Upload.makeRequest (/Users/jonathan/Development/treat-toolbox/functions/node_modules/gcs-resumable-upload/build/src/index.js:348:21)
>      at async Upload.getAndSetOffset (/Users/jonathan/Development/treat-toolbox/functions/node_modules/gcs-resumable-upload/build/src/index.js:298:26)
>      at async Upload.continueUploading (/Users/jonathan/Development/treat-toolbox/functions/node_modules/gcs-resumable-upload/build/src/index.js:182:9)
>  Emitted 'error' event on Pumpify instance at:
>      at errorOrDestroy (/Users/jonathan/Development/treat-toolbox/functions/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
>      at Pumpify.onerror (/Users/jonathan/Development/treat-toolbox/functions/node_modules/readable-stream/lib/_stream_readable.js:704:47)
>      at Pumpify.emit (events.js:315:20)
>      at errorOrDestroy (/Users/jonathan/Development/treat-toolbox/functions/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
>      at onwriteError (/Users/jonathan/Development/treat-toolbox/functions/node_modules/readable-stream/lib/_stream_writable.js:430:5)
>      at onwrite (/Users/jonathan/Development/treat-toolbox/functions/node_modules/readable-stream/lib/_stream_writable.js:450:11)
>      at WritableState.onwrite (/Users/jonathan/Development/treat-toolbox/functions/node_modules/readable-stream/lib/_stream_writable.js:160:5)
>      at Pumpify.Duplexify._destroy (/Users/jonathan/Development/treat-toolbox/functions/node_modules/duplexify/index.js:194:18)
>      at /Users/jonathan/Development/treat-toolbox/functions/node_modules/duplexify/index.js:185:10
>      at processTicksAndRejections (internal/process/task_queues.js:79:11) {
>    response: {
>      config: {
>        method: 'PUT',
>        url: 'http://localhost:9199/upload/storage/v1/b/unicornbillionairesclub.appspot.com/o?name=c15d15d0-fe91-4723-a2ed-9761cadc4064_b_unicornbillionairesclub.appspot.com_o_candy-machine-d1jlAH5FnLMcmyyZ4Ub2-1&uploadType=resumable&upload_id=c15d15d0-fe91-4723-a2ed-9761cadc4064',
>        headers: [Object],
>        validateStatus: [Function],
>        paramsSerializer: [Function: paramsSerializer],
>        responseType: 'json'
>      },
>      data: 'Bad Request',
>      headers: {
>        'access-control-expose-headers': 'content-type,x-firebase-storage-version,x-goog-upload-url,x-goog-upload-status,x-goog-upload-command,x-gupload-uploadid,x-goog-upload-header-content-length,x-goog-upload-header-content-type,x-goog-upload-protocol,x-goog-upload-status,x-goog-upload-chunk-granularity,x-goog-upload-control-url',
>        connection: 'close',
>        'content-length': '11',
>        'content-type': 'text/plain; charset=utf-8',
>        date: 'Sat, 04 Dec 2021 01:47:43 GMT',
>        etag: 'W/"b-EFiDB1U+dmqzx9Mo2UjcZ1SJPO8"',
>        vary: 'Origin',
>        'x-powered-by': 'Express'
>      },
>      status: 400,
>      statusText: 'Bad Request',
>      request: {
>        responseURL: 'http://localhost:9199/upload/storage/v1/b/unicornbillionairesclub.appspot.com/o?name=c15d15d0-fe91-4723-a2ed-9761cadc4064_b_unicornbillionairesclub.appspot.com_o_candy-machine-d1jlAH5FnLMcmyyZ4Ub2-1&uploadType=resumable&upload_id=c15d15d0-fe91-4723-a2ed-9761cadc4064'
>      }
>    },
>    config: {
>      method: 'PUT',
>      url: 'http://localhost:9199/upload/storage/v1/b/unicornbillionairesclub.appspot.com/o?name=c15d15d0-fe91-4723-a2ed-9761cadc4064_b_unicornbillionairesclub.appspot.com_o_candy-machine-d1jlAH5FnLMcmyyZ4Ub2-1&uploadType=resumable&upload_id=c15d15d0-fe91-4723-a2ed-9761cadc4064',
>      headers: {
>        'Content-Length': 0,
>        'Content-Range': 'bytes */*',
>        Accept: 'application/json'
>      },
>      validateStatus: [Function],
>      paramsSerializer: [Function: paramsSerializer],
>      responseType: 'json'
>    },
>    code: '400'
>  }

**Comment by cosimo-rip** [comment]
Are you on the latest version? Some people have had issues with timeouts during export
