### ISSUE TITLE
Composites not generated

### ISSUE THREAD

**Issue by nyoung3** [theskeletoncrew/treat-toolbox#49]
When generating composites, the progress bar immediately fills to 100%, and I see this error in the emulators console

```
Dec 08, 2021 6:45:54 PM io.gapi.emulators.netty.NotFoundHandler handleRequest
INFO: Unknown request URI: /generate-artwork?projectId=REDACTED&collectionId=REDACTED&compositeGroupId=REDACTED&traitSetId=REDACTED&startIndex=0&batchSize=100&isFirstBatchInTraitSet=1
```
And no images are created.

**Comment by skeletoncrewrip** [comment]
it sounds like either the firebase functions arent running, or you havent added the firebase functions url to the environment config file. could that be it?

**Comment by nyoung3** [comment]
my bad, that was what it was. Thank you!
