### ISSUE TITLE
Unhandled Runtime Error: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by bruhjimbo** [theskeletoncrew/treat-toolbox#5]
![image](https://user-images.githubusercontent.com/77355504/137722458-38d30359-4db3-4aa2-af5b-1edb13f93f2d.png)

I have attached image above of error.

I added all my images and data and double checked everything and clicked "generate new composite" and this error occured.

Please help, It took very long to upload all my images and data and I didn't start with data saving on close.

**Comment by fletchertyler914** [comment]
I had this issue when I had traits that did not map to any art.

For example, I created all of my anticipated background color traits (8 total), and I only had 4 background art uploaded and mapped. 

When I removed the traits that did not map to any art it started working fine.

**Comment by cosimo-rip** [comment]
I think the previous comment is likely the issue here. Double check that all of your trait values are mapped. Please reopen the issue if you are still experiencing problems after doing so.
