### ISSUE TITLE
Importing traits from CSV has rounding issues in validation

### ISSUE THREAD

**Issue by wildtangent** [theskeletoncrew/treat-toolbox#50]
When importing a set of trait values by CSV, the total rarity must add up to 1, but dividing many trait values will give you some rounding issues

For example, uploading 17 traits with assorted 0.05 and 0.1 rarity as an example, gives the error "Total rarity did not add up to 1, got 1.00"

Probably need to round the if condition for this to allow for some max number of Decimal places

`if (totalRarity !== 1) { .... `

would become 

```  
const expectedTotal = 1;

if (totalRarity.toFixed(10) !== expectedTotal.toFixed(10)) { ... 
```

**Comment by skeletoncrewrip** [comment]
ahh thanks for the report @wildtangent! we'll take a look at this.
