### ISSUE TITLE
TraitSet checkboxes don't seem to show up as saved in UI

### ISSUE THREAD

**Issue by armyofda12mnkeys** [theskeletoncrew/treat-toolbox#59]
So when I save a Trait checkbox for TraitSet1, it seems to save fine.
Then I added TraitSet2, and then I tried to set the TraitSet2 checkbox for that new Trait, but it seemed to check both TraitSet1 and TraitSet2 when i revisit the Edit page:
The issue occurs here at 1m2seconds... 
https://www.screencast.com/t/I64VVhjYY

You can see I hover over the TraitSet column and it shows TraitSet2, yet the Edit page shows TraitSet1 and TraitSet2. So saving seems to work , but pulling info from db and showing it doesn't seem to work.

In a somewhat related issue, why do some TraitSets show up in the UI as '20'? I can create another ticket for that if needed.

**Comment by KitanGarcia** [comment]
@armyofda12mnkeys Thanks for mentioning this issue and including the screen recording, that was super helpful. I just made a quick fix above, which includes the explanation. For the other issues you've noted, I'd encourage making a separate Issue entry for each one, so they're easy to address.

**Comment by cosimo-rip** [comment]
+1 @armyofda12mnkeys really appreciate the time you put in to demonstrate this issue!
