### ISSUE TITLE
Conflicts resolving not working properly

### ISSUE THREAD

**Issue by jelenajjo** [theskeletoncrew/treat-toolbox#69]
Hey guys, I am trying to generate NFT images with your tool, but I ran into an issue that stops me from finalizing the collection. 

The issue is with conflict resolving when it comes to multiple conditions.

For example:

If I have a headwear trait bandana, I don't want to have eyewear traits sunglasses and VR glasses. So I make resolutions for each:

`If trait 1 bandana - and trait 2 sunglasses - set new random trait 2`
`If trait 1 bandana - and trait 2 VR glasses - set new random trait 2`

I would expect it to never combine bandana with sunglasses and VR glasses, but it still does. 

I guess what happens is that it listens to the first condition, and instead of sunglasses it sets a random trait to be VR glasses. 
Like it doesn't check conditions again, resolving conflict and setting a new trait instead of VR glasses. 

Hopefully, you can understand what I mean. 

Is this a known issue and is it just for the free version? If in paid version this issue is fixed and all working smoothly, I will more than gladly pay!

**Comment by cosimo-rip** [comment]
Hi @jelenajjo - sorry you ran into this issue. 

This is indeed better handled in our pro version, where we make multiple passes to ensure that these sorts of situations are cleared up if the outcome of one conflict ends up hitting another, and regrettably the architectures of PRO and open source have diverged enough that we haven't had much time to back-port these improvements.

Also, if you do give the pro version a try (at https://treattoolbox.com), we would love to hear about your experience coming from the open source version.

**Comment by jelenajjo** [comment]
Okay, I am still testing but so far seems that conflicts in the paid version work well in comparison with the open source version :+1:  Thanks for the fast reply and help!
