### ISSUE TITLE
Composite not working

### ISSUE THREAD

**Issue by lm166796** [theskeletoncrew/treat-toolbox#9]
Recieved the following error -- all items were exported from the same photoshop canvas so should be same size

[firebase-debug.log](https://github.com/theskeletoncrew/treat-toolbox/files/7377960/firebase-debug.log)

**Comment by fletchertyler914** [comment]
You may have more luck pasting the relevant code in a code-block. Most people wont want to download a file to check it out. 

On a side note, I had issues generating a composite when my traits not not completely map to my mapped art.
In other words, I created all of my traits before getting the art done, and when I tried to generate a temporary composite as a test it failed. Once I removed the traits that were unmapped in the art it worked fine.

**Comment by cosimo-rip** [comment]
Please give the latest PR a try: https://github.com/theskeletoncrew/treat-toolbox/pull/31

**Comment by skeletoncrewrip** [comment]
closing - please reopen if you try the new code and still face issues.
